### ISSUE TITLE
Falsche Version im Setup

### ISSUE THREAD

**Issue by bodilS** [dceonline/CONTENIDO#3]
Während des gesamten Setups wird als Version die 4.9.12 genannt:
»Diese Installationsroutine installiert CONTENIDO 4.9.12.«
»Upgraden auf 4.9.12«
»Version 4.9.12«

**Comment by dceonline** [comment]
Ja , das ist leider korrekt. Der erste Release ist eine teil bearbeitete Version ursprünglich aus dem develop-Branch des offiziellen Contenido GIT. Diese Version wurde als initialer Commit as is hier eingestellt.
Entsprechende Änderungen wird es dann für das nächste Release geben.
Danke für die Bug-Meldung!

**Comment by dceonline** [comment]
Versions are corrected in master/development. Closed.
