### ISSUE TITLE
Fehler bei Funktion »Neues Passwort«

### ISSUE THREAD

**Issue by bodilS** [dceonline/CONTENIDO#4]
Nach dem Setup konnte ich mich im Backend nicht anmelden, möglicherweise, weil ich mich bei der Passworteingabe im Setup vertippt habe. Bei der Installation wurde aber in der DB der User sysadmin angelegt. Die Funktion »Neues Passwort« schickt mir zwar einen Link, es erscheint im Loginbereich des Backends auch die Möglichkeit, ein neues Passwort einzugeben, das funktioniert dann aber auch nicht. In der Datenbank hat es im Feld fürs Passwort keine Änderung gegeben, trotz eines völlig anderen Passworts.

**Comment by bodilS** [comment]
Again: Das Passwort, das ich während der Setup-Routine verwendet habe, lässt sich nicht benutzen, um mich anschließend im Backend anzumelden.
Again: Die Funktion zum Ändern des eigenen Passworts mittels Link in einer Mail (»Neues Passwort«) führt zu keiner Veränderung in der Datenbank, ein Anmelden bleibt unmöglich.
Immerhin: die Vergabe unterschiedlicher Passwörter während des Setups hat zu unterschiedlichen Einträgen in der Tabelle con_user geführt. Sowohl in der Spalte password wie auch in der Spalte salt.

**Comment by dceonline** [comment]
Servus,

bitte auch Angaben zu PHP- und MySQL-Versionen machen, damit wir den Bug im entsprechenden Umfeld prüfen können. Danke.

**Comment by dceonline** [comment]
Bug bestätigt. Die aktuelle Version ist nicht mehr kompatibel mit PHP 5.6. Um das Update von älteren Versionen auch unter PHP 5.6 machen zu können, sollte sie das jedoch besser noch sein. Hier müssen wir dann nochmal Hand anlegen.

**Comment by bodilS** [comment]
Hm. Ich frag mich, ob das wirklich sinnvoll ist. Gibt es denn einen anderen gewichtigen Grund, sich sein Contenido upzudaten, außer dass man es auf 7.2 laufen lassen will? Schließlich gibt es da auch noch jene, die dringend auf ein Update warten, weil sie keine andere Option als 7.2 haben. Und deren Geduld wollen wir strapazieren, bis das System auf 5.6 **und** 7.2 **gleichzeitig** läuft?

**Comment by dceonline** [comment]
Ja ist es! So kann man schon im Vorfeld der PHP-Umstellung ein Update machen. Gerade für Admins mit vielen Installationen ist das definitiv ein Vorteil. Dazu müssen ja nun auch keine übermäßigen Purzelbäume gemacht werden, da es sich wohl nur um einige Stelle im Core handelt, die auf PHP 7 umgebaut wurden.
Kurzum, ich denke **WIR** sollten das so machen...

Tja, und daran das es  

> jene, die dringend auf ein Update warten

 gibt, sind wir ja auch nun am wenigsten Schuld.

**Comment by dceonline** [comment]
Commit of a bugfix to develop-branch for Login with PHP 5.6. You may check out and report. Issue will stay open for a week and will be closed if no more request.

**Comment by bodilS** [comment]
Das Problem besteht mit aktuell verfügbarer Installationsdatei leider weiterhin.
PHP 5.6.38
https://github.com/dceonline/CONTENIDO/archive/master.zip

**Comment by dceonline** [comment]
Musste es ja auch, da steht ja auch im develop-Branch gefixt. :)
Nun sollte es aber in beiden Branches funktionieren, also bitte nochmals testen, danke.

**Comment by bodilS** [comment]
Ja, gestestet, jetzt gehts! Dankeschön!

**Comment by dceonline** [comment]
fixed!
Thx for testing.
