### ISSUE TITLE
Falsche Fehlermeldung im HTML-Bereich der Module

### ISSUE THREAD

**Issue by bodilS** [dceonline/CONTENIDO#6]
Klick ich in einem Modul auf den HTML-Tab bekomme ich die Fehlermeldung: »Ihnen fehlen die Schreibberechtigungen für dieses Modul: _MODULNAME_« Trotzdem lassen sich Templates ändern oder anlegen.
CONTENIDO Version | 4.9.13
Webserver-Version | Apache/2.4.29
Installierte PHP-Version | 7.2.3
Datenbankserver-Version | 5.6.19-67.0-log
PHP-Datenbankerweiterung | mysqli
Das Verzeichnis modules hat derzeit 0750, alle untergeordneten Verzeichnisse haben 0777.

**Comment by dceonline** [comment]
Bug bestätigt!

![grafik](https://user-images.githubusercontent.com/8067791/46625402-2b4cee00-cb34-11e8-946a-a79c53ec5e1c.png)

**Comment by dceonline** [comment]
fixed
